def build(bld):
    
    toolchain = bld.env["UsedToolchain"]
    if not toolchain:
        bld.fatal('Environment parameter "UsedToolchain" is not available! Make sure to provide the environment parameter "UsedToolchain" in the root wscript file of your project. e.g.: conf.env["UsedToolchain"] = "gccarmemb"')
    
    platform  = bld.env["UsedPlatform"]
    if not platform:
        bld.fatal('Environment parameter "UsedPlatform" is not available! Make sure to provide the environment parameter "UsedPlatform" in the root wscript file of your project. e.g.: conf.env["UsedPlatform"]  = "netx90"')
    
    comp_prefix = bld.get_name_prefix(
        toolchain = toolchain,
        platform  = platform)

# Component cifXApplicationDemoEIS ---------------------------------------------------------
    netx_studio_sources = [
        "Sources/AppEIS_DemoApplication.c",
		"Sources/AppEIS_DemoApplicationFunctions.c",
        ]

    includes = [
        "Includes",
        ]

    bld.stlib(
        target          = "demoEISV5_simple",
        name            = comp_prefix + "demoEISV5_simple",
        description     = "cifX Application Demo - EtherNet/IP V5 - Simple",
        displaygroup    = "Libraries",
        platform        = platform,
        toolchain       = toolchain, 
        use             = [
                           "Hil_Definition_cifXApi_sdk",
                           "Hil_ProductCode_CIP_sdk",
                           "EIPDefinitions_sdk",
                           "Hil_Definition_netXFirmware_sdk",
                           "hostabstractionlayer_sdk",
                           "cifXApplicationDemo_sdk",
                           "cifXToolkit_sdk",
                           "cifXApplicationDemoConfig_sdk",
                          ],
        source          = netx_studio_sources,
        includes        = includes,
        export_includes = includes,
        defines         = [
                           #"HOST_APPLICATION_SETS_MAC_ADDRESS",        # activate only, if firmware's taglist entry "DDP Mode after firmware startup" 
                                                                        # is configured to "passive"
                           #"HOST_APPLICATION_SETS_SERIAL_NUMBER",      # activate only, if firmware's taglist entry "DDP Mode after firmware startup" 
                                                                        # is configured to "passive"
                           ],
    )
